name: Build and Test Workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      # 1. Clonar el repositorio
      - uses: actions/checkout@v4

      # 2. Instalar dependencias necesarias
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential lcov gcovr git

      # 3. Instalar Google Test
      - name: Install Google Test
        run: |
          echo "Installing Google Test..."
          git clone --depth 1 https://github.com/google/googletest.git /tmp/googletest
          mkdir -p /tmp/googletest/build
          cd /tmp/googletest/build
          cmake .. -DBUILD_GMOCK=OFF -DBUILD_GTEST=ON -DCMAKE_INSTALL_PREFIX=/usr/local
          sudo make install
          echo "Google Test installed."

      # 4. DEBUGGING STEP (KEEP FOR NOW, HELPFUL FOR DIAGNOSIS)
      - name: List Project Files for Debugging
        run: |
          echo "Listing files in the repository root directory:"
          ls -F
          echo ""
          echo "Listing files recursively from the repository root:"
          ls -RF
          echo ""
          echo "Current working directory: $(pwd)"

      # REMOVED the "Copy Source Files to Build Directory" step:
      # This workaround is causing more issues with paths than it solves.
      # We're going back to CMake resolving paths relative to the root.

      # 5. Crear directorio de compilación y configurar el proyecto
      - name: Configure Build System
        run: |
          mkdir -p build
          cd build
          # IMPORTANT: Reverted to cmake ..
          # CMakeLists.txt is in the parent directory (repository root)
          cmake -DENABLE_COVERAGE=ON ..

      # 6. Compilar el código fuente
      - name: Build Project
        run: |
          cd build
          cmake --build .

      # 7. Ejecutar pruebas con salida detallada en caso de error
      - name: Run Unit Tests
        run: |
          cd build
          ctest --output-on-failure

      # 8. Generar informe de cobertura
      - name: Generate Coverage Report
        run: |
          cd build
          # --root should point to the original source root (parent of 'build')
          lcov --capture --directory . --output-file coverage.info --ignore-errors mismatch
          gcovr --root .. --exclude 'tests/*' --exclude 'build/*' --exclude 'main.cpp' --sonarqube -o coverage.xml --print-summary

      # 9. Subir informe de cobertura
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/coverage.xml

  build_analysis:
    name: Build and Analyze
    runs-on: ubuntu-latest
    needs: tests # Este job se ejecuta después de 'tests'

    steps:
      # 1. Clonar el repositorio (con historial necesario para SonarQube)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Descargar el informe de cobertura generado en el job anterior
      - name: Download Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: build/

      # 3. Instalar Google Test para SonarQube
      - name: Install Google Test for SonarQube
        run: |
          echo "Installing Google Test for SonarQube analysis..."
          git clone --depth 1 https://github.com/google/googletest.git /tmp/googletest-sonar
          mkdir -p /tmp/googletest-sonar/build
          cd /tmp/googletest-sonar/build
          cmake .. -DBUILD_GMOCK=OFF -DBUILD_GTEST=ON -DCMAKE_INSTALL_PREFIX=/usr/local
          sudo make install
          echo "Google Test installed for SonarQube."

      # 4. Ejecutar análisis de código con SonarQube
      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          # If SonarQube's analysis requires a fresh build, you might need to
          # include build steps here similar to the 'tests' job, but tailored for SonarQube's
          # build-wrapper if you're using it.
          # For example:
          # args: >
          #   -Dsonar.cfamily.build-wrapper-output=build_wrapper_output_directory
          #   -Dsonar.cfamily.compiler-id=clang
          #   -Dsonar.cfamily.gtest.enabled=true
          #   -Dsonar.inclusions=**/*.h,**/*.cpp
          #   -Dsonar.cfamily.compiler.charset=UTF-8

      # 5. Opcional: Activar Quality Gate para fallar si no se cumplen estándares
      - name: Check SonarQube Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}